### ISSUE TITLE
System window problem

### ISSUE THREAD

**Issue by skillAndroid** [amir1376/compose-custom-window-frame#2]
I tried to open in maximised screen using : state  like  state = WindowState(placement = WindowPlacement.Maximized) but it did not work i would be gratefull if you can answer to this and solve the problem which i am facing )

**Comment by amir1376** [comment]
Hi thanks for reporting this bug
It seems when `Window` class enables the custom decoration, It changes the window's placement!
I pushed a [commit](https://github.com/amir1376/compose-custom-window-frame/releases/tag/1.0.3) to fix that.

You can check it out now.

**Comment by skillAndroid** [comment]
Thank you i will try it again soon
