### ISSUE TITLE
Snap Behaviour not working for Windows 11 and Maximizing fills whole screen

### ISSUE THREAD

**Issue by PMARZV** [amir1376/compose-custom-window-frame#3]
I cloned the whole repository and tried runniong it on a Windows 11 machines and the snap behaviour of touching to borders resizes window, is not working. In addition to this, when maximizing the window there's sometimes a jump like if it was lagging and it always fills the whole screen (even the windows bottom bar)

https://github.com/amir1376/compose-custom-window-frame/assets/100836358/60d4c4b1-bc74-4691-b6e2-30d73dd2d7eb

**Comment by amir1376** [comment]
Are you using [JBR](https://github.com/JetBrains/JetBrainsRuntime) as your project SDK?
